### ISSUE TITLE
Фриз bemtree.

### ISSUE THREAD

**Issue by aliosv** [enb-make/enb-borschik#13]
Дано: нодовое приложение
```
app.get('*', function(req, res) { BEMTREE.apply({ block : 'root' }).then(function(bemjson) {
    res.send(BEMHTML.apply(bemjson));
}) })
```
root.bemtree
```
block('root').def()(function(){
   return {
      block : 'page',
      styles : [{ elem : 'css', url : '/_site.css' }],
      scripts : { elem : 'js', url : '/_site.js' }
   };
})
```
Задача: фризить статику(js, css, ico, ...) и отдавать клиенту подобный html
```
<doctype html>
<head>
    <link href="sha-1.css">
    <script src="sha-1.js">
...
```
Проблемы:
1) enb-borschik ничего не знает про готовность замораживаемых таргетов, т.е. на примере выше _?.css и _?.js таргеты могут не существовать в момент фриза борщиком.
2) Борщик замораживает файлы с определенными расширениями, по умолчанию среди них нет css и js.

**Comment by aliosv** [comment]
https://github.com/enb-make/enb-borschik/pull/12
- технология переписана для использования buildFlow, вместо ручного конфигурирования base-tech.
- удалены легаси опции destTarget и sourceTarget
- добавлена опция для решения пр. 1 - depsTargets
- доб. опция для пр. 2 - freezableExts, но в ней черная магия(https://github.com/aliosv/enb-borschik/blob/master/techs/borschik.js#L65), можно прокидывать расширения иначе: создать технологию борщика на основе тех. js, и переопределить метод isFreezableUrl как в технологии html https://github.com/bem/borschik/blob/master/lib/techs/html.js#L100

**Comment by tormozz48** [comment]
Кажется, что после вливания https://github.com/bem/borschik/pull/97, выпуска новой версии борщика и соответственно обновления зависимости борщика в этом пакете, файлы bemtree,
которые также являются js файлами должны обрабатываться правильным образом

**Comment by aliosv** [comment]
@tormozz48, лично мне не хватает еще json'a.

**Comment by blond** [comment]
@aliosv, json'а как расширения для фриза боршика?

**Comment by aliosv** [comment]
@blond, да
