### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by levonet** [enb-make/enb-borschik#16]
* [x] #18  Implement tests for borschik technology
* [x] #19  Implement tests for js-borschik-include technology

**Comment by tormozz48** [comment]
Кажется, что эту задачу тоже можно закрыть

**Comment by blond** [comment]
Fixed in https://github.com/enb-make/enb-borschik/pull/21, https://github.com/enb-make/enb-borschik/pull/22, https://github.com/enb-make/enb-borschik/pull/23
